// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    FindTheWayOut: typeof import('./src/components/Games/FindTheWayOut.vue')['default']
    GamePresentation: typeof import('./src/components/Games/GamePresentation/GamePresentation.vue')['default']
    Island: typeof import('./src/components/Islands/Island.vue')['default']
    Islands: typeof import('./src/components/Islands/Islands.vue')['default']
    IslandsUI: typeof import('./src/components/Islands/IslandsUI/IslandsUI.vue')['default']
    IslandTitle: typeof import('./src/components/Islands/IslandTitle.vue')['default']
    NumberLink: typeof import('./src/components/Games/NumberLink.vue')['default']
    PauseMenu: typeof import('./src/components/Games/GamesUI/PauseMenu/PauseMenu.vue')['default']
    Results: typeof import('./src/components/Islands/Results.vue')['default']
    TapToContinue: typeof import('./src/components/TapToContinue/TapToContinue.vue')['default']
    TextContainer: typeof import('./src/components/TextContainer/TextContainer.vue')['default']
    WinScreen: typeof import('./src/components/Islands/WinScreen.vue')['default']
  }
}
