// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button/Button.vue')['default']
    CreditView: typeof import('./views/CreditView.vue')['default']
    Dialog: typeof import('./views/Dialog.vue')['default']
    DTButton: typeof import('./components/Button/DTButton.vue')['default']
    FindTheWayOut: typeof import('./components/Games/FindTheWayOut.vue')['default']
    GamePresentation: typeof import('./components/Games/GamePresentation/GamePresentation.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    Island: typeof import('./components/Islands/Island.vue')['default']
    Islands: typeof import('./components/Islands/Islands.vue')['default']
    IslandsUI: typeof import('./components/Islands/IslandsUI/IslandsUI.vue')['default']
    IslandsView: typeof import('./views/IslandsView.vue')['default']
    IslandTitle: typeof import('./components/Islands/IslandTitle.vue')['default']
    IslandView: typeof import('./views/IslandView.vue')['default']
    NumberLink: typeof import('./components/Games/NumberLink.vue')['default']
    PauseMenu: typeof import('./components/Games/GamesUI/PauseMenu/PauseMenu.vue')['default']
    Results: typeof import('./components/Islands/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TapToContinue: typeof import('./components/TapToContinue/TapToContinue.vue')['default']
    TextContainer: typeof import('./components/TextContainer/TextContainer.vue')['default']
    Welcome: typeof import('./views/Welcome.vue')['default']
    WinScreen: typeof import('./components/Islands/WinScreen.vue')['default']
  }
}
