// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[island]': typeof import('./views/islands/[island].vue')['default']
    BottomSheet: typeof import('./components/Common/BottomSheet.vue')['default']
    Card: typeof import('./components/Common/Card.vue')['default']
    CreditView: typeof import('./views/CreditView.vue')['default']
    DesignGame: typeof import('./components/Games/DesignGame/DesignGame.vue')['default']
    Dialog: typeof import('./views/Dialog.vue')['default']
    DTButton: typeof import('./components/Button/DTButton.vue')['default']
    FindTheWayOut: typeof import('./components/Games/FindTheWayOut.vue')['default']
    Game: typeof import('./components/Games/GamesUI/Game.vue')['default']
    GamePresentation: typeof import('./components/Games/GamePresentation/GamePresentation.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    IIcBaselineDraw: typeof import('~icons/ic/baseline-draw')['default']
    IIcBaselineNetworkCheck: typeof import('~icons/ic/baseline-network-check')['default']
    IIcBaselineSecurity: typeof import('~icons/ic/baseline-security')['default']
    IIcOutlineCheckCircle: typeof import('~icons/ic/outline-check-circle')['default']
    IIcOutlineLightbulb: typeof import('~icons/ic/outline-lightbulb')['default']
    IIcOutlineMarkUnreadChatAlt: typeof import('~icons/ic/outline-mark-unread-chat-alt')['default']
    IIcTwotoneSettings: typeof import('~icons/ic/twotone-settings')['default']
    Island: typeof import('./components/Islands/Island.vue')['default']
    Islands: typeof import('./views/islands/index.vue')['default']
    IslandsItems: typeof import('./components/Islands/IslandsItems.vue')['default']
    IslandsUI: typeof import('./components/Islands/IslandsUI/IslandsUI.vue')['default']
    IslandTitle: typeof import('./components/Islands/IslandTitle.vue')['default']
    MaintenanceGame: typeof import('./components/Games/MaintenanceGame.vue')['default']
    NumberLink: typeof import('./components/Games/NumberLink.vue')['default']
    PauseMenu: typeof import('./components/Games/GamesUI/PauseMenu/PauseMenu.vue')['default']
    Results: typeof import('./components/Islands/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepButton: typeof import('./components/Button/StepButton.vue')['default']
    TapToContinue: typeof import('./components/TapToContinue/TapToContinue.vue')['default']
    TextContainer: typeof import('./components/TextContainer/TextContainer.vue')['default']
    Undefined: typeof import('./views/index.vue')['default']
    Welcome: typeof import('./views/Welcome.vue')['default']
    WinScreen: typeof import('./components/Islands/WinScreen.vue')['default']
  }
}
